/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADecfonction extends PDecfonction
{
    private TIdentif _identif_;
    private TParentheseOuvrante _parentheseOuvrante_;
    private PDectab _dectab_;
    private TParentheseFermante _parentheseFermante_;
    private PDecfonction2 _decfonction2_;

    public ADecfonction()
    {
        // Constructor
    }

    public ADecfonction(
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TParentheseOuvrante _parentheseOuvrante_,
        @SuppressWarnings("hiding") PDectab _dectab_,
        @SuppressWarnings("hiding") TParentheseFermante _parentheseFermante_,
        @SuppressWarnings("hiding") PDecfonction2 _decfonction2_)
    {
        // Constructor
        setIdentif(_identif_);

        setParentheseOuvrante(_parentheseOuvrante_);

        setDectab(_dectab_);

        setParentheseFermante(_parentheseFermante_);

        setDecfonction2(_decfonction2_);

    }

    @Override
    public Object clone()
    {
        return new ADecfonction(
            cloneNode(this._identif_),
            cloneNode(this._parentheseOuvrante_),
            cloneNode(this._dectab_),
            cloneNode(this._parentheseFermante_),
            cloneNode(this._decfonction2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecfonction(this);
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TParentheseOuvrante getParentheseOuvrante()
    {
        return this._parentheseOuvrante_;
    }

    public void setParentheseOuvrante(TParentheseOuvrante node)
    {
        if(this._parentheseOuvrante_ != null)
        {
            this._parentheseOuvrante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentheseOuvrante_ = node;
    }

    public PDectab getDectab()
    {
        return this._dectab_;
    }

    public void setDectab(PDectab node)
    {
        if(this._dectab_ != null)
        {
            this._dectab_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dectab_ = node;
    }

    public TParentheseFermante getParentheseFermante()
    {
        return this._parentheseFermante_;
    }

    public void setParentheseFermante(TParentheseFermante node)
    {
        if(this._parentheseFermante_ != null)
        {
            this._parentheseFermante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentheseFermante_ = node;
    }

    public PDecfonction2 getDecfonction2()
    {
        return this._decfonction2_;
    }

    public void setDecfonction2(PDecfonction2 node)
    {
        if(this._decfonction2_ != null)
        {
            this._decfonction2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decfonction2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_)
            + toString(this._parentheseOuvrante_)
            + toString(this._dectab_)
            + toString(this._parentheseFermante_)
            + toString(this._decfonction2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._parentheseOuvrante_ == child)
        {
            this._parentheseOuvrante_ = null;
            return;
        }

        if(this._dectab_ == child)
        {
            this._dectab_ = null;
            return;
        }

        if(this._parentheseFermante_ == child)
        {
            this._parentheseFermante_ = null;
            return;
        }

        if(this._decfonction2_ == child)
        {
            this._decfonction2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._parentheseOuvrante_ == oldChild)
        {
            setParentheseOuvrante((TParentheseOuvrante) newChild);
            return;
        }

        if(this._dectab_ == oldChild)
        {
            setDectab((PDectab) newChild);
            return;
        }

        if(this._parentheseFermante_ == oldChild)
        {
            setParentheseFermante((TParentheseFermante) newChild);
            return;
        }

        if(this._decfonction2_ == oldChild)
        {
            setDecfonction2((PDecfonction2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
