/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADectab2Dectab2 extends PDectab2
{
    private TVirgule _virgule_;
    private PDectab _dectab_;

    public ADectab2Dectab2()
    {
        // Constructor
    }

    public ADectab2Dectab2(
        @SuppressWarnings("hiding") TVirgule _virgule_,
        @SuppressWarnings("hiding") PDectab _dectab_)
    {
        // Constructor
        setVirgule(_virgule_);

        setDectab(_dectab_);

    }

    @Override
    public Object clone()
    {
        return new ADectab2Dectab2(
            cloneNode(this._virgule_),
            cloneNode(this._dectab_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADectab2Dectab2(this);
    }

    public TVirgule getVirgule()
    {
        return this._virgule_;
    }

    public void setVirgule(TVirgule node)
    {
        if(this._virgule_ != null)
        {
            this._virgule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgule_ = node;
    }

    public PDectab getDectab()
    {
        return this._dectab_;
    }

    public void setDectab(PDectab node)
    {
        if(this._dectab_ != null)
        {
            this._dectab_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dectab_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgule_)
            + toString(this._dectab_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgule_ == child)
        {
            this._virgule_ = null;
            return;
        }

        if(this._dectab_ == child)
        {
            this._dectab_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgule_ == oldChild)
        {
            setVirgule((TVirgule) newChild);
            return;
        }

        if(this._dectab_ == oldChild)
        {
            setDectab((PDectab) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
