/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADecfonctionboucleListdecfonction extends PListdecfonction
{
    private PDecfonction _decfonction_;
    private PListdecfonction _listdecfonction_;

    public ADecfonctionboucleListdecfonction()
    {
        // Constructor
    }

    public ADecfonctionboucleListdecfonction(
        @SuppressWarnings("hiding") PDecfonction _decfonction_,
        @SuppressWarnings("hiding") PListdecfonction _listdecfonction_)
    {
        // Constructor
        setDecfonction(_decfonction_);

        setListdecfonction(_listdecfonction_);

    }

    @Override
    public Object clone()
    {
        return new ADecfonctionboucleListdecfonction(
            cloneNode(this._decfonction_),
            cloneNode(this._listdecfonction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecfonctionboucleListdecfonction(this);
    }

    public PDecfonction getDecfonction()
    {
        return this._decfonction_;
    }

    public void setDecfonction(PDecfonction node)
    {
        if(this._decfonction_ != null)
        {
            this._decfonction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decfonction_ = node;
    }

    public PListdecfonction getListdecfonction()
    {
        return this._listdecfonction_;
    }

    public void setListdecfonction(PListdecfonction node)
    {
        if(this._listdecfonction_ != null)
        {
            this._listdecfonction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listdecfonction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decfonction_)
            + toString(this._listdecfonction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decfonction_ == child)
        {
            this._decfonction_ = null;
            return;
        }

        if(this._listdecfonction_ == child)
        {
            this._listdecfonction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decfonction_ == oldChild)
        {
            setDecfonction((PDecfonction) newChild);
            return;
        }

        if(this._listdecfonction_ == oldChild)
        {
            setListdecfonction((PListdecfonction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
