/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADecfonctionListdecfonction extends PListdecfonction
{
    private PDecfonction _decfonction_;

    public ADecfonctionListdecfonction()
    {
        // Constructor
    }

    public ADecfonctionListdecfonction(
        @SuppressWarnings("hiding") PDecfonction _decfonction_)
    {
        // Constructor
        setDecfonction(_decfonction_);

    }

    @Override
    public Object clone()
    {
        return new ADecfonctionListdecfonction(
            cloneNode(this._decfonction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecfonctionListdecfonction(this);
    }

    public PDecfonction getDecfonction()
    {
        return this._decfonction_;
    }

    public void setDecfonction(PDecfonction node)
    {
        if(this._decfonction_ != null)
        {
            this._decfonction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decfonction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decfonction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decfonction_ == child)
        {
            this._decfonction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decfonction_ == oldChild)
        {
            setDecfonction((PDecfonction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
