/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADectabDectab extends PDectab
{
    private TEntier _entier_;
    private PVar _var_;
    private PDectab2 _dectab2_;

    public ADectabDectab()
    {
        // Constructor
    }

    public ADectabDectab(
        @SuppressWarnings("hiding") TEntier _entier_,
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") PDectab2 _dectab2_)
    {
        // Constructor
        setEntier(_entier_);

        setVar(_var_);

        setDectab2(_dectab2_);

    }

    @Override
    public Object clone()
    {
        return new ADectabDectab(
            cloneNode(this._entier_),
            cloneNode(this._var_),
            cloneNode(this._dectab2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADectabDectab(this);
    }

    public TEntier getEntier()
    {
        return this._entier_;
    }

    public void setEntier(TEntier node)
    {
        if(this._entier_ != null)
        {
            this._entier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entier_ = node;
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public PDectab2 getDectab2()
    {
        return this._dectab2_;
    }

    public void setDectab2(PDectab2 node)
    {
        if(this._dectab2_ != null)
        {
            this._dectab2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dectab2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._entier_)
            + toString(this._var_)
            + toString(this._dectab2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._entier_ == child)
        {
            this._entier_ = null;
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._dectab2_ == child)
        {
            this._dectab2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._entier_ == oldChild)
        {
            setEntier((TEntier) newChild);
            return;
        }

        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._dectab2_ == oldChild)
        {
            setDectab2((PDectab2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
