/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AFctExp7 extends PExp7
{
    private PFct _fct_;

    public AFctExp7()
    {
        // Constructor
    }

    public AFctExp7(
        @SuppressWarnings("hiding") PFct _fct_)
    {
        // Constructor
        setFct(_fct_);

    }

    @Override
    public Object clone()
    {
        return new AFctExp7(
            cloneNode(this._fct_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFctExp7(this);
    }

    public PFct getFct()
    {
        return this._fct_;
    }

    public void setFct(PFct node)
    {
        if(this._fct_ != null)
        {
            this._fct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fct_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fct_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fct_ == child)
        {
            this._fct_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fct_ == oldChild)
        {
            setFct((PFct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
