/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstrbloc extends PInstrbloc
{
    private TAccoladeOuvrante _accoladeOuvrante_;
    private PB2 _b2_;
    private TAccoladeFermante _accoladeFermante_;

    public AInstrbloc()
    {
        // Constructor
    }

    public AInstrbloc(
        @SuppressWarnings("hiding") TAccoladeOuvrante _accoladeOuvrante_,
        @SuppressWarnings("hiding") PB2 _b2_,
        @SuppressWarnings("hiding") TAccoladeFermante _accoladeFermante_)
    {
        // Constructor
        setAccoladeOuvrante(_accoladeOuvrante_);

        setB2(_b2_);

        setAccoladeFermante(_accoladeFermante_);

    }

    @Override
    public Object clone()
    {
        return new AInstrbloc(
            cloneNode(this._accoladeOuvrante_),
            cloneNode(this._b2_),
            cloneNode(this._accoladeFermante_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrbloc(this);
    }

    public TAccoladeOuvrante getAccoladeOuvrante()
    {
        return this._accoladeOuvrante_;
    }

    public void setAccoladeOuvrante(TAccoladeOuvrante node)
    {
        if(this._accoladeOuvrante_ != null)
        {
            this._accoladeOuvrante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._accoladeOuvrante_ = node;
    }

    public PB2 getB2()
    {
        return this._b2_;
    }

    public void setB2(PB2 node)
    {
        if(this._b2_ != null)
        {
            this._b2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b2_ = node;
    }

    public TAccoladeFermante getAccoladeFermante()
    {
        return this._accoladeFermante_;
    }

    public void setAccoladeFermante(TAccoladeFermante node)
    {
        if(this._accoladeFermante_ != null)
        {
            this._accoladeFermante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._accoladeFermante_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._accoladeOuvrante_)
            + toString(this._b2_)
            + toString(this._accoladeFermante_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._accoladeOuvrante_ == child)
        {
            this._accoladeOuvrante_ = null;
            return;
        }

        if(this._b2_ == child)
        {
            this._b2_ = null;
            return;
        }

        if(this._accoladeFermante_ == child)
        {
            this._accoladeFermante_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._accoladeOuvrante_ == oldChild)
        {
            setAccoladeOuvrante((TAccoladeOuvrante) newChild);
            return;
        }

        if(this._b2_ == oldChild)
        {
            setB2((PB2) newChild);
            return;
        }

        if(this._accoladeFermante_ == oldChild)
        {
            setAccoladeFermante((TAccoladeFermante) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
