/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AListinstrB2 extends PB2
{
    private PInstr _instr_;
    private PB2 _b2_;

    public AListinstrB2()
    {
        // Constructor
    }

    public AListinstrB2(
        @SuppressWarnings("hiding") PInstr _instr_,
        @SuppressWarnings("hiding") PB2 _b2_)
    {
        // Constructor
        setInstr(_instr_);

        setB2(_b2_);

    }

    @Override
    public Object clone()
    {
        return new AListinstrB2(
            cloneNode(this._instr_),
            cloneNode(this._b2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListinstrB2(this);
    }

    public PInstr getInstr()
    {
        return this._instr_;
    }

    public void setInstr(PInstr node)
    {
        if(this._instr_ != null)
        {
            this._instr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instr_ = node;
    }

    public PB2 getB2()
    {
        return this._b2_;
    }

    public void setB2(PB2 node)
    {
        if(this._b2_ != null)
        {
            this._b2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instr_)
            + toString(this._b2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instr_ == child)
        {
            this._instr_ = null;
            return;
        }

        if(this._b2_ == child)
        {
            this._b2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instr_ == oldChild)
        {
            setInstr((PInstr) newChild);
            return;
        }

        if(this._b2_ == oldChild)
        {
            setB2((PB2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
