/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AListdecvarDecfonction2 extends PDecfonction2
{
    private PDecvar _decvar_;
    private PDecfonction2 _decfonction2_;

    public AListdecvarDecfonction2()
    {
        // Constructor
    }

    public AListdecvarDecfonction2(
        @SuppressWarnings("hiding") PDecvar _decvar_,
        @SuppressWarnings("hiding") PDecfonction2 _decfonction2_)
    {
        // Constructor
        setDecvar(_decvar_);

        setDecfonction2(_decfonction2_);

    }

    @Override
    public Object clone()
    {
        return new AListdecvarDecfonction2(
            cloneNode(this._decvar_),
            cloneNode(this._decfonction2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListdecvarDecfonction2(this);
    }

    public PDecvar getDecvar()
    {
        return this._decvar_;
    }

    public void setDecvar(PDecvar node)
    {
        if(this._decvar_ != null)
        {
            this._decvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decvar_ = node;
    }

    public PDecfonction2 getDecfonction2()
    {
        return this._decfonction2_;
    }

    public void setDecfonction2(PDecfonction2 node)
    {
        if(this._decfonction2_ != null)
        {
            this._decfonction2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decfonction2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decvar_)
            + toString(this._decfonction2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decvar_ == child)
        {
            this._decvar_ = null;
            return;
        }

        if(this._decfonction2_ == child)
        {
            this._decfonction2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decvar_ == oldChild)
        {
            setDecvar((PDecvar) newChild);
            return;
        }

        if(this._decfonction2_ == oldChild)
        {
            setDecfonction2((PDecfonction2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
