/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASinonsiS2 extends PS2
{
    private TSinon _sinon_;
    private PInstrsi _instrsi_;

    public ASinonsiS2()
    {
        // Constructor
    }

    public ASinonsiS2(
        @SuppressWarnings("hiding") TSinon _sinon_,
        @SuppressWarnings("hiding") PInstrsi _instrsi_)
    {
        // Constructor
        setSinon(_sinon_);

        setInstrsi(_instrsi_);

    }

    @Override
    public Object clone()
    {
        return new ASinonsiS2(
            cloneNode(this._sinon_),
            cloneNode(this._instrsi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinonsiS2(this);
    }

    public TSinon getSinon()
    {
        return this._sinon_;
    }

    public void setSinon(TSinon node)
    {
        if(this._sinon_ != null)
        {
            this._sinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinon_ = node;
    }

    public PInstrsi getInstrsi()
    {
        return this._instrsi_;
    }

    public void setInstrsi(PInstrsi node)
    {
        if(this._instrsi_ != null)
        {
            this._instrsi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrsi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sinon_)
            + toString(this._instrsi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sinon_ == child)
        {
            this._sinon_ = null;
            return;
        }

        if(this._instrsi_ == child)
        {
            this._instrsi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sinon_ == oldChild)
        {
            setSinon((TSinon) newChild);
            return;
        }

        if(this._instrsi_ == oldChild)
        {
            setInstrsi((PInstrsi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
