/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.parser;

import sc.lexer.*;
import sc.node.*;
import sc.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgramme node1 = (PProgramme) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AProgramme */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce ADecvarBase */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce AVoidBase */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce ADecfonctionboucleListdecfonction */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list, false);
            }
            break;
            case 4: /* reduce ADecfonctionListdecfonction */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list, false);
            }
            break;
            case 5: /* reduce ADecvarInstr */
            {
                ArrayList<Object> list = new5();
                push(goTo(3), list, false);
            }
            break;
            case 6: /* reduce AInstrtantqueInstr */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list, false);
            }
            break;
            case 7: /* reduce AInstraffectInstr */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list, false);
            }
            break;
            case 8: /* reduce AInstrblocInstr */
            {
                ArrayList<Object> list = new8();
                push(goTo(3), list, false);
            }
            break;
            case 9: /* reduce AInstrsiInstr */
            {
                ArrayList<Object> list = new9();
                push(goTo(3), list, false);
            }
            break;
            case 10: /* reduce AInstrappelInstr */
            {
                ArrayList<Object> list = new10();
                push(goTo(3), list, false);
            }
            break;
            case 11: /* reduce AInstrretourInstr */
            {
                ArrayList<Object> list = new11();
                push(goTo(3), list, false);
            }
            break;
            case 12: /* reduce AInstrecritureInstr */
            {
                ArrayList<Object> list = new12();
                push(goTo(3), list, false);
            }
            break;
            case 13: /* reduce AInstrvideInstr */
            {
                ArrayList<Object> list = new13();
                push(goTo(3), list, false);
            }
            break;
            case 14: /* reduce AInstrtantque */
            {
                ArrayList<Object> list = new14();
                push(goTo(4), list, false);
            }
            break;
            case 15: /* reduce AInstraffect */
            {
                ArrayList<Object> list = new15();
                push(goTo(5), list, false);
            }
            break;
            case 16: /* reduce AListinstrB2 */
            {
                ArrayList<Object> list = new16();
                push(goTo(6), list, false);
            }
            break;
            case 17: /* reduce AInstrfinB2 */
            {
                ArrayList<Object> list = new17();
                push(goTo(6), list, false);
            }
            break;
            case 18: /* reduce AInstrsi */
            {
                ArrayList<Object> list = new18();
                push(goTo(7), list, false);
            }
            break;
            case 19: /* reduce ASinonsiS2 */
            {
                ArrayList<Object> list = new19();
                push(goTo(8), list, false);
            }
            break;
            case 20: /* reduce ASinonS2 */
            {
                ArrayList<Object> list = new20();
                push(goTo(8), list, false);
            }
            break;
            case 21: /* reduce AVideS2 */
            {
                ArrayList<Object> list = new21();
                push(goTo(8), list, false);
            }
            break;
            case 22: /* reduce AInstrappel */
            {
                ArrayList<Object> list = new22();
                push(goTo(9), list, false);
            }
            break;
            case 23: /* reduce AInstrretour */
            {
                ArrayList<Object> list = new23();
                push(goTo(10), list, false);
            }
            break;
            case 24: /* reduce AInstrecriture */
            {
                ArrayList<Object> list = new24();
                push(goTo(11), list, false);
            }
            break;
            case 25: /* reduce AInstrvide */
            {
                ArrayList<Object> list = new25();
                push(goTo(12), list, false);
            }
            break;
            case 26: /* reduce ADectabDectab */
            {
                ArrayList<Object> list = new26();
                push(goTo(13), list, false);
            }
            break;
            case 27: /* reduce AVideDectab */
            {
                ArrayList<Object> list = new27();
                push(goTo(13), list, false);
            }
            break;
            case 28: /* reduce ADectab2Dectab2 */
            {
                ArrayList<Object> list = new28();
                push(goTo(14), list, false);
            }
            break;
            case 29: /* reduce AVideDectab2 */
            {
                ArrayList<Object> list = new29();
                push(goTo(14), list, false);
            }
            break;
            case 30: /* reduce ADecvar */
            {
                ArrayList<Object> list = new30();
                push(goTo(15), list, false);
            }
            break;
            case 31: /* reduce ADecvar2Decvar2 */
            {
                ArrayList<Object> list = new31();
                push(goTo(16), list, false);
            }
            break;
            case 32: /* reduce AListdecvarDecvar2 */
            {
                ArrayList<Object> list = new32();
                push(goTo(16), list, false);
            }
            break;
            case 33: /* reduce ADecfonction */
            {
                ArrayList<Object> list = new33();
                push(goTo(17), list, false);
            }
            break;
            case 34: /* reduce AIntrblocDecfonction2 */
            {
                ArrayList<Object> list = new34();
                push(goTo(18), list, false);
            }
            break;
            case 35: /* reduce AListdecvarDecfonction2 */
            {
                ArrayList<Object> list = new35();
                push(goTo(18), list, false);
            }
            break;
            case 36: /* reduce AInstrbloc */
            {
                ArrayList<Object> list = new36();
                push(goTo(19), list, false);
            }
            break;
            case 37: /* reduce AOuExp */
            {
                ArrayList<Object> list = new37();
                push(goTo(20), list, false);
            }
            break;
            case 38: /* reduce AExp2Exp */
            {
                ArrayList<Object> list = new38();
                push(goTo(20), list, false);
            }
            break;
            case 39: /* reduce AEtExp2 */
            {
                ArrayList<Object> list = new39();
                push(goTo(21), list, false);
            }
            break;
            case 40: /* reduce AExp3Exp2 */
            {
                ArrayList<Object> list = new40();
                push(goTo(21), list, false);
            }
            break;
            case 41: /* reduce AEgalExp3 */
            {
                ArrayList<Object> list = new41();
                push(goTo(22), list, false);
            }
            break;
            case 42: /* reduce AInferieurExp3 */
            {
                ArrayList<Object> list = new42();
                push(goTo(22), list, false);
            }
            break;
            case 43: /* reduce AExp4Exp3 */
            {
                ArrayList<Object> list = new43();
                push(goTo(22), list, false);
            }
            break;
            case 44: /* reduce APlusExp4 */
            {
                ArrayList<Object> list = new44();
                push(goTo(23), list, false);
            }
            break;
            case 45: /* reduce AMoinsExp4 */
            {
                ArrayList<Object> list = new45();
                push(goTo(23), list, false);
            }
            break;
            case 46: /* reduce AExp5Exp4 */
            {
                ArrayList<Object> list = new46();
                push(goTo(23), list, false);
            }
            break;
            case 47: /* reduce AFoisExp5 */
            {
                ArrayList<Object> list = new47();
                push(goTo(24), list, false);
            }
            break;
            case 48: /* reduce ADiviseExp5 */
            {
                ArrayList<Object> list = new48();
                push(goTo(24), list, false);
            }
            break;
            case 49: /* reduce AExp6Exp5 */
            {
                ArrayList<Object> list = new49();
                push(goTo(24), list, false);
            }
            break;
            case 50: /* reduce ANonExp6 */
            {
                ArrayList<Object> list = new50();
                push(goTo(25), list, false);
            }
            break;
            case 51: /* reduce AExp7Exp6 */
            {
                ArrayList<Object> list = new51();
                push(goTo(25), list, false);
            }
            break;
            case 52: /* reduce AParentheseExp7 */
            {
                ArrayList<Object> list = new52();
                push(goTo(26), list, false);
            }
            break;
            case 53: /* reduce AFctExp7 */
            {
                ArrayList<Object> list = new53();
                push(goTo(26), list, false);
            }
            break;
            case 54: /* reduce ANombreExp7 */
            {
                ArrayList<Object> list = new54();
                push(goTo(26), list, false);
            }
            break;
            case 55: /* reduce AVarExp7 */
            {
                ArrayList<Object> list = new55();
                push(goTo(26), list, false);
            }
            break;
            case 56: /* reduce ALireExp7 */
            {
                ArrayList<Object> list = new56();
                push(goTo(26), list, false);
            }
            break;
            case 57: /* reduce AFct */
            {
                ArrayList<Object> list = new57();
                push(goTo(27), list, false);
            }
            break;
            case 58: /* reduce AListeexpListeexp */
            {
                ArrayList<Object> list = new58();
                push(goTo(28), list, false);
            }
            break;
            case 59: /* reduce AVideListeexp */
            {
                ArrayList<Object> list = new59();
                push(goTo(28), list, false);
            }
            break;
            case 60: /* reduce AExpbisExpbis */
            {
                ArrayList<Object> list = new60();
                push(goTo(29), list, false);
            }
            break;
            case 61: /* reduce AVideExpbis */
            {
                ArrayList<Object> list = new61();
                push(goTo(29), list, false);
            }
            break;
            case 62: /* reduce AVarVar */
            {
                ArrayList<Object> list = new62();
                push(goTo(30), list, false);
            }
            break;
            case 63: /* reduce ATabVar */
            {
                ArrayList<Object> list = new63();
                push(goTo(30), list, false);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AProgramme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PBase pbaseNode2;
        PListdecfonction plistdecfonctionNode3;
        pbaseNode2 = (PBase)nodeArrayList1.get(0);
        plistdecfonctionNode3 = (PListdecfonction)nodeArrayList2.get(0);

        pprogrammeNode1 = new AProgramme(pbaseNode2, plistdecfonctionNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce ADecvarBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PBase pbaseNode1;
        {
            // Block
        PDecvar pdecvarNode2;
        pdecvarNode2 = (PDecvar)nodeArrayList1.get(0);

        pbaseNode1 = new ADecvarBase(pdecvarNode2);
        }
	nodeList.add(pbaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AVoidBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PBase pbaseNode1;
        {
            // Block

        pbaseNode1 = new AVoidBase();
        }
	nodeList.add(pbaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce ADecfonctionboucleListdecfonction */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListdecfonction plistdecfonctionNode1;
        {
            // Block
        PDecfonction pdecfonctionNode2;
        PListdecfonction plistdecfonctionNode3;
        pdecfonctionNode2 = (PDecfonction)nodeArrayList1.get(0);
        plistdecfonctionNode3 = (PListdecfonction)nodeArrayList2.get(0);

        plistdecfonctionNode1 = new ADecfonctionboucleListdecfonction(pdecfonctionNode2, plistdecfonctionNode3);
        }
	nodeList.add(plistdecfonctionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ADecfonctionListdecfonction */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListdecfonction plistdecfonctionNode1;
        {
            // Block
        PDecfonction pdecfonctionNode2;
        pdecfonctionNode2 = (PDecfonction)nodeArrayList1.get(0);

        plistdecfonctionNode1 = new ADecfonctionListdecfonction(pdecfonctionNode2);
        }
	nodeList.add(plistdecfonctionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ADecvarInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PDecvar pdecvarNode2;
        pdecvarNode2 = (PDecvar)nodeArrayList1.get(0);

        pinstrNode1 = new ADecvarInstr(pdecvarNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AInstrtantqueInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstrtantque pinstrtantqueNode2;
        pinstrtantqueNode2 = (PInstrtantque)nodeArrayList1.get(0);

        pinstrNode1 = new AInstrtantqueInstr(pinstrtantqueNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AInstraffectInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstraffect pinstraffectNode2;
        pinstraffectNode2 = (PInstraffect)nodeArrayList1.get(0);

        pinstrNode1 = new AInstraffectInstr(pinstraffectNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AInstrblocInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstrbloc pinstrblocNode2;
        pinstrblocNode2 = (PInstrbloc)nodeArrayList1.get(0);

        pinstrNode1 = new AInstrblocInstr(pinstrblocNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AInstrsiInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstrsi pinstrsiNode2;
        pinstrsiNode2 = (PInstrsi)nodeArrayList1.get(0);

        pinstrNode1 = new AInstrsiInstr(pinstrsiNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AInstrappelInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstrappel pinstrappelNode2;
        pinstrappelNode2 = (PInstrappel)nodeArrayList1.get(0);

        pinstrNode1 = new AInstrappelInstr(pinstrappelNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce AInstrretourInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstrretour pinstrretourNode2;
        pinstrretourNode2 = (PInstrretour)nodeArrayList1.get(0);

        pinstrNode1 = new AInstrretourInstr(pinstrretourNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AInstrecritureInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstrecriture pinstrecritureNode2;
        pinstrecritureNode2 = (PInstrecriture)nodeArrayList1.get(0);

        pinstrNode1 = new AInstrecritureInstr(pinstrecritureNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce AInstrvideInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PInstrvide pinstrvideNode2;
        pinstrvideNode2 = (PInstrvide)nodeArrayList1.get(0);

        pinstrNode1 = new AInstrvideInstr(pinstrvideNode2);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AInstrtantque */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrtantque pinstrtantqueNode1;
        {
            // Block
        TTantque ttantqueNode2;
        PExp pexpNode3;
        TFaire tfaireNode4;
        PInstrbloc pinstrblocNode5;
        ttantqueNode2 = (TTantque)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tfaireNode4 = (TFaire)nodeArrayList3.get(0);
        pinstrblocNode5 = (PInstrbloc)nodeArrayList4.get(0);

        pinstrtantqueNode1 = new AInstrtantque(ttantqueNode2, pexpNode3, tfaireNode4, pinstrblocNode5);
        }
	nodeList.add(pinstrtantqueNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce AInstraffect */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstraffect pinstraffectNode1;
        {
            // Block
        PVar pvarNode2;
        TEgal tegalNode3;
        PExp pexpNode4;
        TPointVirgule tpointvirguleNode5;
        pvarNode2 = (PVar)nodeArrayList1.get(0);
        tegalNode3 = (TEgal)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tpointvirguleNode5 = (TPointVirgule)nodeArrayList4.get(0);

        pinstraffectNode1 = new AInstraffect(pvarNode2, tegalNode3, pexpNode4, tpointvirguleNode5);
        }
	nodeList.add(pinstraffectNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AListinstrB2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PB2 pb2Node1;
        {
            // Block
        PInstr pinstrNode2;
        PB2 pb2Node3;
        pinstrNode2 = (PInstr)nodeArrayList1.get(0);
        pb2Node3 = (PB2)nodeArrayList2.get(0);

        pb2Node1 = new AListinstrB2(pinstrNode2, pb2Node3);
        }
	nodeList.add(pb2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AInstrfinB2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PB2 pb2Node1;
        {
            // Block
        PInstr pinstrNode2;
        pinstrNode2 = (PInstr)nodeArrayList1.get(0);

        pb2Node1 = new AInstrfinB2(pinstrNode2);
        }
	nodeList.add(pb2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AInstrsi */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrsi pinstrsiNode1;
        {
            // Block
        TSi tsiNode2;
        PExp pexpNode3;
        TAlors talorsNode4;
        PInstrbloc pinstrblocNode5;
        PS2 ps2Node6;
        tsiNode2 = (TSi)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        talorsNode4 = (TAlors)nodeArrayList3.get(0);
        pinstrblocNode5 = (PInstrbloc)nodeArrayList4.get(0);
        ps2Node6 = (PS2)nodeArrayList5.get(0);

        pinstrsiNode1 = new AInstrsi(tsiNode2, pexpNode3, talorsNode4, pinstrblocNode5, ps2Node6);
        }
	nodeList.add(pinstrsiNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce ASinonsiS2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PS2 ps2Node1;
        {
            // Block
        TSinon tsinonNode2;
        PInstrsi pinstrsiNode3;
        tsinonNode2 = (TSinon)nodeArrayList1.get(0);
        pinstrsiNode3 = (PInstrsi)nodeArrayList2.get(0);

        ps2Node1 = new ASinonsiS2(tsinonNode2, pinstrsiNode3);
        }
	nodeList.add(ps2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce ASinonS2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PS2 ps2Node1;
        {
            // Block
        TSinon tsinonNode2;
        PInstrbloc pinstrblocNode3;
        tsinonNode2 = (TSinon)nodeArrayList1.get(0);
        pinstrblocNode3 = (PInstrbloc)nodeArrayList2.get(0);

        ps2Node1 = new ASinonS2(tsinonNode2, pinstrblocNode3);
        }
	nodeList.add(ps2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AVideS2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PS2 ps2Node1;
        {
            // Block

        ps2Node1 = new AVideS2();
        }
	nodeList.add(ps2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AInstrappel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrappel pinstrappelNode1;
        {
            // Block
        TIdentif tidentifNode2;
        TParentheseOuvrante tparentheseouvranteNode3;
        PListeexp plisteexpNode4;
        TParentheseFermante tparenthesefermanteNode5;
        TPointVirgule tpointvirguleNode6;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);
        tparentheseouvranteNode3 = (TParentheseOuvrante)nodeArrayList2.get(0);
        plisteexpNode4 = (PListeexp)nodeArrayList3.get(0);
        tparenthesefermanteNode5 = (TParentheseFermante)nodeArrayList4.get(0);
        tpointvirguleNode6 = (TPointVirgule)nodeArrayList5.get(0);

        pinstrappelNode1 = new AInstrappel(tidentifNode2, tparentheseouvranteNode3, plisteexpNode4, tparenthesefermanteNode5, tpointvirguleNode6);
        }
	nodeList.add(pinstrappelNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AInstrretour */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrretour pinstrretourNode1;
        {
            // Block
        TRetour tretourNode2;
        PExp pexpNode3;
        TPointVirgule tpointvirguleNode4;
        tretourNode2 = (TRetour)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tpointvirguleNode4 = (TPointVirgule)nodeArrayList3.get(0);

        pinstrretourNode1 = new AInstrretour(tretourNode2, pexpNode3, tpointvirguleNode4);
        }
	nodeList.add(pinstrretourNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AInstrecriture */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrecriture pinstrecritureNode1;
        {
            // Block
        TEcrire tecrireNode2;
        TParentheseOuvrante tparentheseouvranteNode3;
        PListeexp plisteexpNode4;
        TParentheseFermante tparenthesefermanteNode5;
        TPointVirgule tpointvirguleNode6;
        tecrireNode2 = (TEcrire)nodeArrayList1.get(0);
        tparentheseouvranteNode3 = (TParentheseOuvrante)nodeArrayList2.get(0);
        plisteexpNode4 = (PListeexp)nodeArrayList3.get(0);
        tparenthesefermanteNode5 = (TParentheseFermante)nodeArrayList4.get(0);
        tpointvirguleNode6 = (TPointVirgule)nodeArrayList5.get(0);

        pinstrecritureNode1 = new AInstrecriture(tecrireNode2, tparentheseouvranteNode3, plisteexpNode4, tparenthesefermanteNode5, tpointvirguleNode6);
        }
	nodeList.add(pinstrecritureNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AInstrvide */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrvide pinstrvideNode1;
        {
            // Block
        TPointVirgule tpointvirguleNode2;
        tpointvirguleNode2 = (TPointVirgule)nodeArrayList1.get(0);

        pinstrvideNode1 = new AInstrvide(tpointvirguleNode2);
        }
	nodeList.add(pinstrvideNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce ADectabDectab */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDectab pdectabNode1;
        {
            // Block
        TEntier tentierNode2;
        PVar pvarNode3;
        PDectab2 pdectab2Node4;
        tentierNode2 = (TEntier)nodeArrayList1.get(0);
        pvarNode3 = (PVar)nodeArrayList2.get(0);
        pdectab2Node4 = (PDectab2)nodeArrayList3.get(0);

        pdectabNode1 = new ADectabDectab(tentierNode2, pvarNode3, pdectab2Node4);
        }
	nodeList.add(pdectabNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AVideDectab */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PDectab pdectabNode1;
        {
            // Block

        pdectabNode1 = new AVideDectab();
        }
	nodeList.add(pdectabNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce ADectab2Dectab2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDectab2 pdectab2Node1;
        {
            // Block
        TVirgule tvirguleNode2;
        PDectab pdectabNode3;
        tvirguleNode2 = (TVirgule)nodeArrayList1.get(0);
        pdectabNode3 = (PDectab)nodeArrayList2.get(0);

        pdectab2Node1 = new ADectab2Dectab2(tvirguleNode2, pdectabNode3);
        }
	nodeList.add(pdectab2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AVideDectab2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PDectab2 pdectab2Node1;
        {
            // Block

        pdectab2Node1 = new AVideDectab2();
        }
	nodeList.add(pdectab2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce ADecvar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecvar pdecvarNode1;
        {
            // Block
        TEntier tentierNode2;
        PVar pvarNode3;
        PDecvar2 pdecvar2Node4;
        tentierNode2 = (TEntier)nodeArrayList1.get(0);
        pvarNode3 = (PVar)nodeArrayList2.get(0);
        pdecvar2Node4 = (PDecvar2)nodeArrayList3.get(0);

        pdecvarNode1 = new ADecvar(tentierNode2, pvarNode3, pdecvar2Node4);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce ADecvar2Decvar2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecvar2 pdecvar2Node1;
        {
            // Block
        TPointVirgule tpointvirguleNode2;
        tpointvirguleNode2 = (TPointVirgule)nodeArrayList1.get(0);

        pdecvar2Node1 = new ADecvar2Decvar2(tpointvirguleNode2);
        }
	nodeList.add(pdecvar2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AListdecvarDecvar2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecvar2 pdecvar2Node1;
        {
            // Block
        TVirgule tvirguleNode2;
        PDecvar pdecvarNode3;
        tvirguleNode2 = (TVirgule)nodeArrayList1.get(0);
        pdecvarNode3 = (PDecvar)nodeArrayList2.get(0);

        pdecvar2Node1 = new AListdecvarDecvar2(tvirguleNode2, pdecvarNode3);
        }
	nodeList.add(pdecvar2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce ADecfonction */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonction pdecfonctionNode1;
        {
            // Block
        TIdentif tidentifNode2;
        TParentheseOuvrante tparentheseouvranteNode3;
        PDectab pdectabNode4;
        TParentheseFermante tparenthesefermanteNode5;
        PDecfonction2 pdecfonction2Node6;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);
        tparentheseouvranteNode3 = (TParentheseOuvrante)nodeArrayList2.get(0);
        pdectabNode4 = (PDectab)nodeArrayList3.get(0);
        tparenthesefermanteNode5 = (TParentheseFermante)nodeArrayList4.get(0);
        pdecfonction2Node6 = (PDecfonction2)nodeArrayList5.get(0);

        pdecfonctionNode1 = new ADecfonction(tidentifNode2, tparentheseouvranteNode3, pdectabNode4, tparenthesefermanteNode5, pdecfonction2Node6);
        }
	nodeList.add(pdecfonctionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AIntrblocDecfonction2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonction2 pdecfonction2Node1;
        {
            // Block
        PInstrbloc pinstrblocNode2;
        pinstrblocNode2 = (PInstrbloc)nodeArrayList1.get(0);

        pdecfonction2Node1 = new AIntrblocDecfonction2(pinstrblocNode2);
        }
	nodeList.add(pdecfonction2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AListdecvarDecfonction2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonction2 pdecfonction2Node1;
        {
            // Block
        PDecvar pdecvarNode2;
        PDecfonction2 pdecfonction2Node3;
        pdecvarNode2 = (PDecvar)nodeArrayList1.get(0);
        pdecfonction2Node3 = (PDecfonction2)nodeArrayList2.get(0);

        pdecfonction2Node1 = new AListdecvarDecfonction2(pdecvarNode2, pdecfonction2Node3);
        }
	nodeList.add(pdecfonction2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AInstrbloc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrbloc pinstrblocNode1;
        {
            // Block
        TAccoladeOuvrante taccoladeouvranteNode2;
        PB2 pb2Node3;
        TAccoladeFermante taccoladefermanteNode4;
        taccoladeouvranteNode2 = (TAccoladeOuvrante)nodeArrayList1.get(0);
        pb2Node3 = (PB2)nodeArrayList2.get(0);
        taccoladefermanteNode4 = (TAccoladeFermante)nodeArrayList3.get(0);

        pinstrblocNode1 = new AInstrbloc(taccoladeouvranteNode2, pb2Node3, taccoladefermanteNode4);
        }
	nodeList.add(pinstrblocNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce AOuExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TOu touNode3;
        PExp2 pexp2Node4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        touNode3 = (TOu)nodeArrayList2.get(0);
        pexp2Node4 = (PExp2)nodeArrayList3.get(0);

        pexpNode1 = new AOuExp(pexpNode2, touNode3, pexp2Node4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AExp2Exp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp2 pexp2Node2;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);

        pexpNode1 = new AExp2Exp(pexp2Node2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce AEtExp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp2 pexp2Node2;
        TEt tetNode3;
        PExp3 pexp3Node4;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);
        tetNode3 = (TEt)nodeArrayList2.get(0);
        pexp3Node4 = (PExp3)nodeArrayList3.get(0);

        pexp2Node1 = new AEtExp2(pexp2Node2, tetNode3, pexp3Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AExp3Exp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp3 pexp3Node2;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);

        pexp2Node1 = new AExp3Exp2(pexp3Node2);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AEgalExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TEgal tegalNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tegalNode3 = (TEgal)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new AEgalExp3(pexp3Node2, tegalNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce AInferieurExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TInferieur tinferieurNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tinferieurNode3 = (TInferieur)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new AInferieurExp3(pexp3Node2, tinferieurNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce AExp4Exp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp4 pexp4Node2;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);

        pexp3Node1 = new AExp4Exp3(pexp4Node2);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce APlusExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TPlus tplusNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new APlusExp4(pexp4Node2, tplusNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AMoinsExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TMoins tmoinsNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tmoinsNode3 = (TMoins)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new AMoinsExp4(pexp4Node2, tmoinsNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AExp5Exp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp5 pexp5Node2;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);

        pexp4Node1 = new AExp5Exp4(pexp5Node2);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce AFoisExp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp5 pexp5Node2;
        TFois tfoisNode3;
        PExp6 pexp6Node4;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);
        tfoisNode3 = (TFois)nodeArrayList2.get(0);
        pexp6Node4 = (PExp6)nodeArrayList3.get(0);

        pexp5Node1 = new AFoisExp5(pexp5Node2, tfoisNode3, pexp6Node4);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce ADiviseExp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp5 pexp5Node2;
        TDivise tdiviseNode3;
        PExp6 pexp6Node4;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);
        tdiviseNode3 = (TDivise)nodeArrayList2.get(0);
        pexp6Node4 = (PExp6)nodeArrayList3.get(0);

        pexp5Node1 = new ADiviseExp5(pexp5Node2, tdiviseNode3, pexp6Node4);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce AExp6Exp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp6 pexp6Node2;
        pexp6Node2 = (PExp6)nodeArrayList1.get(0);

        pexp5Node1 = new AExp6Exp5(pexp6Node2);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce ANonExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TNon tnonNode2;
        PExp6 pexp6Node3;
        tnonNode2 = (TNon)nodeArrayList1.get(0);
        pexp6Node3 = (PExp6)nodeArrayList2.get(0);

        pexp6Node1 = new ANonExp6(tnonNode2, pexp6Node3);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce AExp7Exp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        PExp7 pexp7Node2;
        pexp7Node2 = (PExp7)nodeArrayList1.get(0);

        pexp6Node1 = new AExp7Exp6(pexp7Node2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce AParentheseExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TParentheseOuvrante tparentheseouvranteNode2;
        PExp pexpNode3;
        TParentheseFermante tparenthesefermanteNode4;
        tparentheseouvranteNode2 = (TParentheseOuvrante)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tparenthesefermanteNode4 = (TParentheseFermante)nodeArrayList3.get(0);

        pexp7Node1 = new AParentheseExp7(tparentheseouvranteNode2, pexpNode3, tparenthesefermanteNode4);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce AFctExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        PFct pfctNode2;
        pfctNode2 = (PFct)nodeArrayList1.get(0);

        pexp7Node1 = new AFctExp7(pfctNode2);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce ANombreExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TNombre tnombreNode2;
        tnombreNode2 = (TNombre)nodeArrayList1.get(0);

        pexp7Node1 = new ANombreExp7(tnombreNode2);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce AVarExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        PVar pvarNode2;
        pvarNode2 = (PVar)nodeArrayList1.get(0);

        pexp7Node1 = new AVarExp7(pvarNode2);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new56() /* reduce ALireExp7 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp7 pexp7Node1;
        {
            // Block
        TLire tlireNode2;
        TParentheseOuvrante tparentheseouvranteNode3;
        TParentheseFermante tparenthesefermanteNode4;
        tlireNode2 = (TLire)nodeArrayList1.get(0);
        tparentheseouvranteNode3 = (TParentheseOuvrante)nodeArrayList2.get(0);
        tparenthesefermanteNode4 = (TParentheseFermante)nodeArrayList3.get(0);

        pexp7Node1 = new ALireExp7(tlireNode2, tparentheseouvranteNode3, tparenthesefermanteNode4);
        }
	nodeList.add(pexp7Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new57() /* reduce AFct */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFct pfctNode1;
        {
            // Block
        TIdentif tidentifNode2;
        TParentheseOuvrante tparentheseouvranteNode3;
        PListeexp plisteexpNode4;
        TParentheseFermante tparenthesefermanteNode5;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);
        tparentheseouvranteNode3 = (TParentheseOuvrante)nodeArrayList2.get(0);
        plisteexpNode4 = (PListeexp)nodeArrayList3.get(0);
        tparenthesefermanteNode5 = (TParentheseFermante)nodeArrayList4.get(0);

        pfctNode1 = new AFct(tidentifNode2, tparentheseouvranteNode3, plisteexpNode4, tparenthesefermanteNode5);
        }
	nodeList.add(pfctNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new58() /* reduce AListeexpListeexp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListeexp plisteexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExpbis pexpbisNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpbisNode3 = (PExpbis)nodeArrayList2.get(0);

        plisteexpNode1 = new AListeexpListeexp(pexpNode2, pexpbisNode3);
        }
	nodeList.add(plisteexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new59() /* reduce AVideListeexp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListeexp plisteexpNode1;
        {
            // Block

        plisteexpNode1 = new AVideListeexp();
        }
	nodeList.add(plisteexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new60() /* reduce AExpbisExpbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpbis pexpbisNode1;
        {
            // Block
        TVirgule tvirguleNode2;
        PExp pexpNode3;
        PExpbis pexpbisNode4;
        tvirguleNode2 = (TVirgule)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        pexpbisNode4 = (PExpbis)nodeArrayList3.get(0);

        pexpbisNode1 = new AExpbisExpbis(tvirguleNode2, pexpNode3, pexpbisNode4);
        }
	nodeList.add(pexpbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new61() /* reduce AVideExpbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PExpbis pexpbisNode1;
        {
            // Block

        pexpbisNode1 = new AVideExpbis();
        }
	nodeList.add(pexpbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new62() /* reduce AVarVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TIdentif tidentifNode2;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);

        pvarNode1 = new AVarVar(tidentifNode2);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new63() /* reduce ATabVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TIdentif tidentifNode2;
        TCrochetOuvrant tcrochetouvrantNode3;
        PExp pexpNode4;
        TCrochetFermant tcrochetfermantNode5;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);
        tcrochetouvrantNode3 = (TCrochetOuvrant)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tcrochetfermantNode5 = (TCrochetFermant)nodeArrayList4.get(0);

        pvarNode1 = new ATabVar(tidentifNode2, tcrochetouvrantNode3, pexpNode4, tcrochetfermantNode5);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 2}, {4, SHIFT, 1}, },
			{{-1, ERROR, 1}, {27, SHIFT, 5}, },
			{{-1, ERROR, 2}, {28, ACCEPT, -1}, },
			{{-1, ERROR, 3}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 62}, {15, SHIFT, 10}, },
			{{-1, ERROR, 6}, {8, SHIFT, 11}, {25, SHIFT, 12}, },
			{{-1, ERROR, 7}, {13, SHIFT, 14}, },
			{{-1, REDUCE, 0}, },
			{{-1, REDUCE, 4}, {27, SHIFT, 7}, },
			{{-1, ERROR, 10}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 12}, {4, SHIFT, 1}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 27}, {4, SHIFT, 31}, },
			{{-1, REDUCE, 3}, },
			{{-1, ERROR, 16}, {13, SHIFT, 33}, },
			{{-1, ERROR, 17}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 18}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 62}, {13, SHIFT, 36}, {15, SHIFT, 10}, },
			{{-1, ERROR, 21}, {16, SHIFT, 37}, {23, SHIFT, 38}, },
			{{-1, REDUCE, 38}, {22, SHIFT, 39}, },
			{{-1, REDUCE, 40}, {19, SHIFT, 40}, {21, SHIFT, 41}, },
			{{-1, REDUCE, 43}, {9, SHIFT, 42}, {10, SHIFT, 43}, },
			{{-1, REDUCE, 46}, {11, SHIFT, 44}, {12, SHIFT, 45}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 31}, {27, SHIFT, 5}, },
			{{-1, ERROR, 32}, {14, SHIFT, 47}, },
			{{-1, ERROR, 33}, {14, SHIFT, 48}, },
			{{-1, ERROR, 34}, {14, SHIFT, 49}, {23, SHIFT, 38}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 59}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 63}, },
			{{-1, ERROR, 38}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 39}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 40}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 41}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 42}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 43}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 44}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 45}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 29}, {25, SHIFT, 60}, },
			{{-1, ERROR, 47}, {4, SHIFT, 1}, {17, SHIFT, 62}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 61}, {23, SHIFT, 38}, {25, SHIFT, 66}, },
			{{-1, ERROR, 51}, {14, SHIFT, 68}, },
			{{-1, REDUCE, 37}, {22, SHIFT, 39}, },
			{{-1, REDUCE, 39}, {19, SHIFT, 40}, {21, SHIFT, 41}, },
			{{-1, REDUCE, 41}, {9, SHIFT, 42}, {10, SHIFT, 43}, },
			{{-1, REDUCE, 42}, {9, SHIFT, 42}, {10, SHIFT, 43}, },
			{{-1, REDUCE, 44}, {11, SHIFT, 44}, {12, SHIFT, 45}, },
			{{-1, REDUCE, 45}, {11, SHIFT, 44}, {12, SHIFT, 45}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 27}, {4, SHIFT, 31}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 62}, {0, SHIFT, 70}, {4, SHIFT, 1}, {5, SHIFT, 71}, {7, SHIFT, 72}, {8, SHIFT, 73}, {17, SHIFT, 62}, {20, SHIFT, 74}, {27, SHIFT, 75}, },
			{{-1, ERROR, 63}, {4, SHIFT, 1}, {17, SHIFT, 62}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 66}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 70}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 71}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 72}, {13, SHIFT, 92}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 74}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 62}, {13, SHIFT, 94}, {15, SHIFT, 10}, },
			{{-1, REDUCE, 17}, {0, SHIFT, 70}, {4, SHIFT, 1}, {5, SHIFT, 71}, {7, SHIFT, 72}, {8, SHIFT, 73}, {17, SHIFT, 62}, {20, SHIFT, 74}, {27, SHIFT, 75}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 79}, {18, SHIFT, 96}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 87}, {19, SHIFT, 97}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 61}, {23, SHIFT, 38}, {25, SHIFT, 66}, },
			{{-1, ERROR, 90}, {1, SHIFT, 99}, {23, SHIFT, 38}, },
			{{-1, ERROR, 91}, {8, SHIFT, 100}, {23, SHIFT, 38}, },
			{{-1, REDUCE, 59}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, ERROR, 93}, {3, SHIFT, 102}, {23, SHIFT, 38}, },
			{{-1, REDUCE, 59}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 36}, },
			{{-1, ERROR, 97}, {6, SHIFT, 16}, {13, SHIFT, 17}, {24, SHIFT, 18}, {26, SHIFT, 19}, {27, SHIFT, 20}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 99}, {17, SHIFT, 62}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 101}, {14, SHIFT, 106}, },
			{{-1, ERROR, 102}, {17, SHIFT, 62}, },
			{{-1, ERROR, 103}, {14, SHIFT, 108}, },
			{{-1, ERROR, 104}, {8, SHIFT, 109}, {23, SHIFT, 38}, },
			{{-1, REDUCE, 21}, {2, SHIFT, 110}, },
			{{-1, ERROR, 106}, {8, SHIFT, 112}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 108}, {8, SHIFT, 113}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 110}, {0, SHIFT, 70}, {17, SHIFT, 62}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 20}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 8}, {9, 15}, },
			{{-1, 76}, },
			{{-1, 77}, },
			{{-1, 78}, },
			{{-1, 79}, {76, 95}, },
			{{-1, 80}, {110, 114}, },
			{{-1, 111}, },
			{{-1, 81}, },
			{{-1, 82}, },
			{{-1, 83}, },
			{{-1, 84}, },
			{{-1, 32}, {60, 69}, },
			{{-1, 61}, },
			{{-1, 63}, {0, 4}, {12, 30}, {62, 85}, {76, 85}, },
			{{-1, 13}, },
			{{-1, 9}, },
			{{-1, 64}, {63, 88}, },
			{{-1, 65}, {62, 86}, {76, 86}, {99, 105}, {102, 107}, {110, 115}, },
			{{-1, 50}, {10, 21}, {17, 34}, {66, 89}, {70, 90}, {71, 91}, {74, 93}, {97, 104}, },
			{{-1, 22}, {38, 52}, },
			{{-1, 23}, {39, 53}, },
			{{-1, 24}, {40, 54}, {41, 55}, },
			{{-1, 25}, {42, 56}, {43, 57}, },
			{{-1, 26}, {18, 35}, {44, 58}, {45, 59}, },
			{{-1, 27}, },
			{{-1, 28}, },
			{{-1, 51}, {92, 101}, {94, 103}, },
			{{-1, 67}, {89, 98}, },
			{{-1, 29}, {1, 6}, {31, 46}, {62, 87}, {76, 87}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'entier', identif",
			"expecting: identif",
			"expecting: EOF",
			"expecting: ';', ')', '[', ','",
			"expecting: ';', ','",
			"expecting: '('",
			"expecting: identif, EOF",
			"expecting: 'lire', '(', '!', nombre, identif",
			"expecting: 'si', 'entier', 'retour', 'ecrire', ';', '{', '}', 'tantque', identif",
			"expecting: 'entier'",
			"expecting: 'entier', ')'",
			"expecting: 'alors', 'faire', ';', '+', '-', '*', '/', ')', ']', '=', '<', '&', '|', ','",
			"expecting: 'alors', 'faire', ';', '+', '-', '*', '/', '(', ')', '[', ']', '=', '<', '&', '|', ','",
			"expecting: ']', '|'",
			"expecting: 'alors', 'faire', ';', ')', ']', '&', '|', ','",
			"expecting: 'alors', 'faire', ';', ')', ']', '=', '<', '&', '|', ','",
			"expecting: 'alors', 'faire', ';', '+', '-', ')', ']', '=', '<', '&', '|', ','",
			"expecting: ')'",
			"expecting: ')', '|'",
			"expecting: 'lire', '(', ')', '!', nombre, identif",
			"expecting: ')', ','",
			"expecting: 'entier', '{'",
			"expecting: ')', '|', ','",
			"expecting: 'si', 'entier', 'retour', 'ecrire', ';', '{', 'tantque', identif",
			"expecting: '(', '[', '='",
			"expecting: '}'",
			"expecting: '='",
			"expecting: 'alors', '|'",
			"expecting: ';', '|'",
			"expecting: 'faire', '|'",
			"expecting: 'si', 'sinon', 'entier', 'retour', 'ecrire', ';', '{', '}', 'tantque', identif, EOF",
			"expecting: '{'",
			"expecting: 'si', 'sinon', 'entier', 'retour', 'ecrire', ';', '{', '}', 'tantque', identif",
			"expecting: ';'",
			"expecting: 'si', '{'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 1, 1, 3, 4, 5, 2, 6, 7, 8, 9, 8, 10, 2, 5, 7, 7, 11, 12, 13, 14, 15, 16, 11, 11, 11, 11, 11, 8, 1, 17, 17, 18, 11, 19, 11, 7, 7, 7, 7, 7, 7, 7, 7, 20, 21, 11, 11, 22, 17, 14, 15, 16, 16, 11, 11, 11, 11, 10, 17, 23, 21, 6, 6, 7, 17, 11, 17, 7, 7, 5, 8, 7, 24, 8, 8, 8, 25, 8, 8, 8, 8, 8, 8, 8, 26, 6, 22, 27, 28, 19, 29, 19, 25, 30, 7, 17, 31, 8, 17, 31, 17, 28, 32, 33, 8, 33, 8, 34, 8, 8, 8, 8, 8, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
